server:
  port: ${PORT:8080} # ???????? ?????????? ?????????:???????? ?? ?????????

kafka-properties:
    topic: registry-processing
    topic-partitions: 2
    topic-replicas: 2
    back-off-interval: 60000
    max-retry-attempts: 9223372036854775807


spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      enable-auto-commit: false
      ack-mode: manual
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        # ?????? > ???????????? ??? ???????? ???????????? ????? (literal block scalar).
        # ??? ????????, ??? ??? ??????? ????? ????, ??????? ??????? ? ???????? ??????, ????? ?????????????? ??? ????? ????????, ??? ?????-???? ??????????? ?????????????.
        # ?????? - ? ?????? ??????, ????????? ?? >, ????????? ?? ??, ??? ???? ??????????? ???? ????? ???????? ????????? ?????
        spring.json.type.mapping: >-
          messagePayload:com.spring_tutorials.spring_kafka.dto.kafka.MessagePayload
        spring.json.trusted.packages: org.springframework.batch.integration.partition
        session.timeout.ms: 60000
        heartbeat.interval.ms: 20000
        max.poll.interval.ms: 20000
    admin:
      fail-fast: true
    listener:
      idle-between-polls: 1000